import { Header } from "@/app/components/header/header";
import { Providers } from "@/components/providers";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Toaster } from "react-hot-toast";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} flex min-h-screen w-screen flex-col bg-background px-20 pt-[100px] font-geist-sans text-sm font-medium text-text ${geistMono.variable} antialiased`}
      >
        <Providers>
          <Header />
          {children}

          {/* TODO: Customize toaster styling */}
          <Toaster />
        </Providers>
      </body>
    </html>
  );
}
